import "./globals.css";
import Head from "next/head";
import Provider from "./component/Provider";

export const metadata = {
  title: "Merry-Match",
  description: "Generated by create next app",
  icons: {
    icon: [
      "https://hzhhjgfmkxwvwsdteigk.supabase.co/storage/v1/object/public/user-storage/icons/merry-logo.svg",
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="icon" href="../../merry-logo.ico" />
      </Head>
      <html lang="en">
        <Provider>
          <body>{children}</body>
        </Provider>
      </html>
    </>
  );
}
